# Generated by Django 4.2.7 on 2026-03-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
