# Generated by Django 4.2.7 on 2026-03-11 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_campuslocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='campuslocation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campuslocation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
