# Generated by Django 4.2.7 on 2026-03-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_campuslocation_latitude_campuslocation_longitude'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_active',
            new_name='active',
        ),
        migrations.AddField(
            model_name='category',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
