# Generated by Django 4.2.7 on 2026-02-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_item', 'New Item Posted'), ('item_claimed', 'Item Claimed'), ('password_changed', 'Password Changed'), ('item_found', 'Matching Item Found'), ('new_message', 'New Chat Message'), ('general', 'General')], default='general', max_length=30),
        ),
        migrations.AddField(
            model_name='notification',
            name='play_sound',
            field=models.BooleanField(default=True),
        ),
    ]
