# Generated by Django 4.2.7 on 2026-03-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_item', 'New Item Posted'), ('item_claimed', 'Item Claimed'), ('password_changed', 'Password Changed'), ('item_found', 'Matching Item Found'), ('new_message', 'New Chat Message'), ('claim_request', 'Claim Request'), ('claim_accepted', 'Claim Accepted'), ('claim_rejected', 'Claim Rejected'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
