# Generated by Django 4.2.7 on 2026-03-04 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_forwarded_from_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.chatroom'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_item', 'New Item Posted'), ('item_claimed', 'Item Claimed'), ('password_changed', 'Password Changed'), ('item_found', 'Matching Item Found'), ('new_message', 'New Chat Message'), ('chat_message', 'New Chat Message'), ('claim_request', 'Claim Request'), ('claim_accepted', 'Claim Accepted'), ('claim_rejected', 'Claim Rejected'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
