# Generated by Django 4.2.7 on 2026-03-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_chat_notification_sender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='sender',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_item', 'New Item Posted'), ('item_claimed', 'Item Claimed'), ('password_changed', 'Password Changed'), ('item_found', 'Matching Item Found'), ('new_message', 'New Chat Message'), ('general', 'General')], default='general', max_length=30),
        ),
    ]
