import os
import django
from django.db import connection

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'campustrace_backend.settings')
django.setup()

def create_rewards_table():
    sql = """
    CREATE TABLE IF NOT EXISTS "users_rewardtransaction" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
        "points" integer NOT NULL, 
        "description" varchar(255) NOT NULL, 
        "category" varchar(20) NOT NULL, 
        "timestamp" timestamptz NOT NULL, 
        "item_id" bigint NULL, 
        "user_id" bigint NOT NULL
    );
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_item_fk') THEN
            ALTER TABLE "users_rewardtransaction" ADD CONSTRAINT "reward_item_fk" FOREIGN KEY ("item_id") REFERENCES "items" ("id") DEFERRABLE INITIALLY DEFERRED;
        END IF;
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'reward_user_fk') THEN
            ALTER TABLE "users_rewardtransaction" ADD CONSTRAINT "reward_user_fk" FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
        END IF;
    END $$;
    CREATE INDEX IF NOT EXISTS "users_rewardtransaction_item_id_idx" ON "users_rewardtransaction" ("item_id");
    CREATE INDEX IF NOT EXISTS "users_rewardtransaction_user_id_idx" ON "users_rewardtransaction" ("user_id");
    """
    
    with connection.cursor() as cursor:
        print("Creating users_rewardtransaction table...")
        cursor.execute(sql)
        print("Table created (or already existed).")

if __name__ == "__main__":
    create_rewards_table()
