# Generated by Django 6.0.2 on 2026-02-21 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('books', 'Books'), ('keys', 'Keys'), ('wallet', 'Wallet'), ('id_card', 'ID Card'), ('clothing', 'Clothing'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=50)),
                ('type', models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=10)),
                ('location', models.CharField(choices=[('library', 'Library'), ('hostel', 'Hostel'), ('canteen', 'Canteen'), ('classroom', 'Classroom Block'), ('parking', 'Parking Area'), ('student_union', 'Student Union'), ('gym', 'Gym'), ('science_block', 'Science Block'), ('other', 'Other')], default='other', max_length=100)),
                ('location_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('closed', 'Closed')], default='active', max_length=20)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_occurred', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_items', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-created_at'],
            },
        ),
    ]
