# Generated by Django 4.2.7 on 2026-02-28 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_location_name_item_use_current_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_occurred',
            new_name='incident_datetime',
        ),
    ]
