# Generated by Django 4.2.7 on 2026-02-28 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('items', '0003_rename_date_occurred_item_incident_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='colleges.block'),
        ),
        migrations.AddField(
            model_name='item',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='colleges.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='colleges.college'),
        ),
    ]
