# Generated by Django 4.2.7 on 2026-03-02 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0004_item_block_item_category_new_item_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='unique_mark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('claimed', 'Claimed'), ('returned', 'Returned'), ('closed', 'Closed')], default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.IntegerField(default=0)),
                ('is_verified_owner', models.BooleanField(default=False)),
                ('claim_code', models.CharField(blank=True, max_length=6, null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_made', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='items.item')),
            ],
            options={
                'db_table': 'claim_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
