# Generated by Django 4.2.7 on 2026-03-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_item_brand_item_color_item_unique_mark_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claimrequest',
            old_name='correct_answers',
            new_name='correct_score',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='is_verified_owner',
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='answers',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
