# Generated by Django 4.2.7 on 2026-03-02 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0006_rename_correct_answers_claimrequest_correct_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ai_verified', 'AI Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('ai_score', models.IntegerField(default=0)),
                ('claim_code', models.CharField(blank=True, max_length=6, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims_sessions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_sessions', to='items.item')),
            ],
            options={
                'db_table': 'claim_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ClaimRequest',
        ),
    ]
