# Generated by Django 4.2.7 on 2026-03-02 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_claimsession_delete_claimrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsession',
            name='ai_questions',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='claimsession',
            name='user_answers',
            field=models.JSONField(default=dict),
        ),
    ]
