# Generated by Django 4.2.7 on 2026-03-03 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_claimsession_ai_questions_claimsession_user_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsession',
            name='current_question_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='claimsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
