# Generated by Django 4.2.7 on 2026-03-03 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_campuslocation'),
        ('items', '0009_claimsession_current_question_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='colleges.campuslocation'),
        ),
    ]
