# Generated by Django 4.2.7 on 2026-03-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_item_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
