# Generated by Django 4.2.7 on 2026-03-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_claimsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsession',
            name='code_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claimsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('awaiting_code_generation', 'Awaiting Code Generation'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
