# Generated by Django 4.2.7 on 2026-03-04 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0012_claimsession_code_generated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected'), ('awaiting_code_generation', 'Awaiting Code Generation'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_code', models.CharField(blank=True, max_length=6, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finder_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finder_user_claims', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to='items.item')),
                ('lost_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_user_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claim_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
