# Generated by Django 4.2.7 on 2026-03-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_alter_claimsession_status_claimrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('awaiting_code_generation', 'Awaiting Code Generation'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('completed', 'Completed')], default='pending', max_length=30),
        ),
    ]
