# Generated by Django 4.2.7 on 2026-03-05 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_alter_claimsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='verification_answers',
            field=models.JSONField(blank=True, help_text='Stored answers from foundation user', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='verification_questions',
            field=models.JSONField(blank=True, help_text='List of questions for electronics verification', null=True),
        ),
    ]
