# Generated by Django 4.2.7 on 2026-03-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_item_verification_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claimsession',
            name='ai_confidence',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
