# Generated by Django 4.2.7 on 2026-03-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0018_claimrequest_ai_result_alter_claimsession_ai_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='from_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='from_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_path',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='path_distance',
            field=models.FloatField(blank=True, help_text='Distance in kilometers', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='to_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='to_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
