# Generated by Django 4.2.7 on 2026-03-11 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('items', '0019_item_from_latitude_item_from_longitude_item_is_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claimsession',
            name='ai_confidence',
        ),
        migrations.RemoveField(
            model_name='claimsession',
            name='ai_result',
        ),
        migrations.RemoveField(
            model_name='claimsession',
            name='code_generated_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='from_latitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='from_longitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_path',
        ),
        migrations.RemoveField(
            model_name='item',
            name='path_distance',
        ),
        migrations.RemoveField(
            model_name='item',
            name='to_latitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='to_longitude',
        ),
        migrations.RemoveField(
            model_name='item',
            name='verification_answers',
        ),
        migrations.RemoveField(
            model_name='item',
            name='verification_questions',
        ),
        migrations.AddField(
            model_name='claimsession',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claimsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClaimRequest',
        ),
    ]
