# Generated by Django 4.2.7 on 2026-03-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_remove_claimsession_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='claim_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
