# Generated by Django 4.2.7 on 2026-03-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0022_claimsession_ai_result_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='unique_mark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
