# Generated by Django 4.2.7 on 2026-03-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_alter_item_unique_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='verification_answers',
            field=models.JSONField(blank=True, help_text='Answers provided by the founder', null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='verification_questions',
            field=models.JSONField(blank=True, help_text='List of 5 questions generated by AI', null=True),
        ),
    ]
