# Generated by Django 4.2.7 on 2026-03-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0025_claimsession_ai_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Market price of the item', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated reward for the finder', max_digits=10, null=True),
        ),
    ]
