from django.db import models
from users.models import User
import random
import string


class Item(models.Model):
    TYPE_CHOICES = [
        ('lost', 'Lost'),
        ('found', 'Found'),
    ]

    STATUS_CHOICES = [
        ('active', 'Active'),
        ('claimed', 'Claimed'),
        ('returned', 'Returned'),
        ('closed', 'Closed'),
    ]

    CATEGORY_CHOICES = [
        ('electronics', 'Electronics'),
        ('books', 'Books'),
        ('keys', 'Keys'),
        ('wallet', 'Wallet'),
        ('id_card', 'ID Card'),
        ('clothing', 'Clothing'),
        ('accessories', 'Accessories'),
        ('other', 'Other'),
    ]

    LOCATION_CHOICES = [
        ('library', 'Library'),
        ('hostel', 'Hostel'),
        ('canteen', 'Canteen'),
        ('classroom', 'Classroom Block'),
        ('parking', 'Parking Area'),
        ('student_union', 'Student Union'),
        ('gym', 'Gym'),
        ('science_block', 'Science Block'),
        ('other', 'Other'),
    ]

    title = models.CharField(max_length=200)
    description = models.TextField()
    brand = models.CharField(max_length=100, blank=True, null=True)
    color = models.CharField(max_length=50, blank=True, null=True)
    unique_mark = models.TextField(blank=True, null=True)
    category = models.CharField(max_length=50, choices=CATEGORY_CHOICES, default='other')
    type = models.CharField(max_length=10, choices=TYPE_CHOICES)
    location = models.CharField(max_length=100, choices=LOCATION_CHOICES, default='other')
    
    # Multi-College fields
    college = models.ForeignKey('colleges.College', on_delete=models.CASCADE, related_name='items', null=True, blank=True)
    category_new = models.ForeignKey('colleges.Category', on_delete=models.SET_NULL, null=True, blank=True, related_name='items')
    block = models.ForeignKey('colleges.CampusLocation', on_delete=models.SET_NULL, null=True, blank=True, related_name='items')
    
    location_detail = models.CharField(max_length=200, blank=True, null=True)
    location_name = models.CharField(max_length=300, blank=True, null=True)  # GPS address text
    use_current_location = models.BooleanField(default=False)
    latitude = models.FloatField(blank=True, null=True)
    longitude = models.FloatField(blank=True, null=True)
    
    # Store questions and answers for electronic item verification
    verification_questions = models.JSONField(null=True, blank=True, help_text="List of 5 questions generated by AI")
    verification_answers = models.JSONField(null=True, blank=True, help_text="Answers provided by the founder")
    

    
    image = models.ImageField(upload_to='items/', blank=True, null=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='active')
    contact_phone = models.CharField(max_length=20, blank=True, null=True)
    reference_number = models.CharField(max_length=20, unique=True, blank=True)
    claim_code = models.CharField(max_length=6, blank=True, null=True)
    incident_datetime = models.DateTimeField(blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='items')
    claimed_by = models.ForeignKey(
        User, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='claimed_items'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'items'
        ordering = ['-created_at']

    def __str__(self):
        return f"[{self.type.upper()}] {self.title} - {self.status}"

    def get_location_display_text(self):
        """Return GPS address if used, otherwise dropdown label"""
        if self.use_current_location and self.location_name:
            return self.location_name
        return self.get_location_display()

    def get_map_label(self):
        """Shows 'Lost here' or 'Found here' on map pin"""
        if self.type == 'lost':
            return 'Lost here'
        return 'Found here'

    def is_electronics(self):
        """Returns True if the item falls into a category requiring AI verification"""
        ELECTRONICS_CATEGORIES = [
            "Mobile Phones",
            "Earbuds",
            "Laptops",
            "Tablets",
            "Smart Watches",
            "Camera",
            "Headphones",
            "Other electronics",
            "Electronics"
        ]
        
        # Check new dynamic category system first
        if self.category_new and self.category_new.name in ELECTRONICS_CATEGORIES:
            return True
        
        # Fallback to old legacy choices if needed
        if self.category == "electronics":
            return True
            
        return False

    def save(self, *args, **kwargs):
        # Generate reference number
        if not self.reference_number:
            prefix = 'LF' if self.type == 'lost' else 'FF'
            suffix = ''.join(random.choices(string.digits, k=4))
            self.reference_number = f"{prefix}-{suffix}"

        # Claimed status only allowed for lost items
        if self.type == 'found' and self.status == 'claimed':
            self.status = 'closed'

        super().save(*args, **kwargs)


class ItemPhoto(models.Model):
    """Multiple photos per item"""
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='photos')
    photo = models.ImageField(upload_to='items/photos/')
    is_primary = models.BooleanField(default=False)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'item_photos'
        ordering = ['-is_primary', 'uploaded_at']

    def __str__(self):
        return f"Photo for {self.item.title} (primary={self.is_primary})"


class ClaimSession(models.Model):
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='claim_sessions')
    claimant = models.ForeignKey(User, on_delete=models.CASCADE, related_name='claims_sessions')
    status = models.CharField(
        max_length=20,
        choices=[
            ("pending", "Pending"),
            ("verified", "Verified"),
            ("failed", "Failed"),
            ("completed", "Completed"),
        ],
        default="pending"
    )
    ai_score = models.IntegerField(default=0)
    ai_result_label = models.CharField(max_length=50, blank=True, null=True)
    ai_result = models.CharField(max_length=50, default="PENDING")
    current_question_index = models.IntegerField(default=0)
    ai_questions = models.JSONField(default=list)
    user_answers = models.JSONField(default=dict)
    claim_code = models.CharField(max_length=6, blank=True, null=True)
    attempts = models.IntegerField(default=0)
    approver = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True, blank=True, related_name='approved_claims')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = 'claim_sessions'
        ordering = ['-created_at']

    def __str__(self):
        return f"Claim Session for {self.item.title} by {self.claimant.username}"