# Generated by Django 4.2.7 on 2026-03-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(default='', max_length=20)),
                ('college_name', models.CharField(max_length=255)),
                ('college_id_card', models.ImageField(blank=True, null=True, upload_to='admin_requests/college_id/')),
                ('aadhaar_card', models.ImageField(blank=True, null=True, upload_to='admin_requests/aadhaar/')),
                ('designation', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(default='')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'admin_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
