# Generated by Django 4.2.7 on 2026-03-12 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_helpcategory_alter_adminrequest_options_helptopic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helptopic',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='adminrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='HelpCategory',
        ),
        migrations.DeleteModel(
            name='HelpTopic',
        ),
    ]
