# Generated by Django 4.2.7 on 2026-04-08 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardpayment',
            name='proof_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardpayment',
            name='proof_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rewardpayment',
            name='proof_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofs_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rewardpayment',
            name='return_proof',
            field=models.FileField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AlterField(
            model_name='rewardpayment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid (Escrow)'), ('held', 'Held in Escrow'), ('proof_pending', 'Proof Pending'), ('released', 'Completed (Released)'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20),
        ),
    ]
