# Generated by Django 4.2.7 on 2026-04-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_rewardpayment_proof_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardpayment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid (Escrow)'), ('held', 'Held in Escrow'), ('proof_pending', 'Proof Pending'), ('proof_verified', 'Proof Verified'), ('proof_rejected', 'Proof Rejected'), ('released', 'Completed (Released)'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='created', max_length=20),
        ),
    ]
