# Generated by Django 4.2.7 on 2026-02-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_notification_enabled_user_sound_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notification_enabled',
            new_name='email_notifications',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='sound_enabled',
            new_name='notification_sound',
        ),
        migrations.AddField(
            model_name='passwordresettoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
