# Generated by Django 4.2.7 on 2026-02-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_dark_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_known_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_known_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
