# Generated by Django 4.2.7 on 2026-03-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_college_user_is_blocked_user_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='successful_returns',
            field=models.IntegerField(default=0),
        ),
    ]
