# Generated by Django 4.2.7 on 2026-03-11 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0020_remove_claimsession_ai_confidence_and_more'),
        ('users', '0008_user_points_user_successful_returns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='points',
            new_name='reward_points',
        ),
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default='Beginner Helper', max_length=50),
        ),
        migrations.CreateModel(
            name='RewardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('return', 'Successful Return'), ('reporting', 'Reporting Found Item'), ('approval', 'Approving Verification'), ('bonus', 'Bonus Points')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
