# Generated by Django 4.2.7 on 2026-03-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_points_user_reward_points_user_badges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='trust_score',
            field=models.IntegerField(default=100),
        ),
    ]
